name: CI/CD PIPELINE FOR MYFUNCTIONAPP

#  Workflow Trigger
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.gitignore'
  pull_request:
    branches: [ main ]
  
# Define environment variables
env:
  AZURE_FUNCTIONAPP_NAME: 'myfunctionappz'
  PYTHON_VERSION: '3.11'
  WORKING_DIR: '.'


  
jobs:
  quality-check:
    name: Test & Verify
    runs-on: ubuntu-latest
    steps:
    - name: Get code
      uses: actions/checkout@v3
      
    - name: Configure Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: pip
        
        # Setup Dependencies
    - name: Setup dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install pytest pytest-asyncio
        pip install -r requirements.txt
        
    #Run tests
    - name: Run test suite
      run: |
        echo "Running tests for TaskHub API..."
        pytest -v
      env:
        AZURE_TABLES_CONNECTION_STRING: ${{ secrets.AZURE_TABLES_CONNECTION_STRING }}  

        # Deploy to Azure Function App
  deploy-function:
    name: Deploy to Azure
    needs: quality-check
    if: github.event_name == 'push' || github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
    - name: Get code
      uses: actions/checkout@v3
      
    - name: Configure Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Bundle dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
        
    # Secure Credential Management     
    - name: Authenticate with Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} 
        
    - name: Deploy Function App
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.WORKING_DIR }}
        scm-do-build-during-deployment: true
        enable-oryx-build: true
        
        #Log the deployment completion time 
    - name: Log deployment status
      run: |
        echo "Deployment completed at $(date)"
        echo "Function App URL: https://${{ env.AZURE_FUNCTIONAPP_NAME }}.azurewebsites.net"